services:
  app:
    build: .
    container_name: wallet_app
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_NAME=${DB_NAME:-wallet_db}
      - DB_SSLMODE=disable
      - SERVER_PORT=8080
      - DB_RESET=${DB_RESET:-false}
    depends_on:
      - db
    networks:
      - wallet-network
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: wallet_db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-wallet_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - wallet-network

volumes:
  postgres_data:

networks:
  wallet-network:
    driver: bridge